kind: ConfigMap
apiVersion: v1
metadata:
  name: pod-simulator-1-ca
  namespace: {{ $.Values.demoapp.environment }}-{{ $.Values.demoapp.serviceLine }}-{{ $.Values.demoapp.namespacesuffix }}
data:
  rollout.action: rollout
  amq.url: openshift-activemq-forward
